-- ─── PAYMENTS TABLE ─────────────────────────────────────────
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS payments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  package_id      UUID REFERENCES packages(id) ON DELETE SET NULL,   -- packages.id is UUID
  package_number  INT,
  amount          BIGINT NOT NULL DEFAULT 0,   -- stored in full VNĐ (e.g. 15000000)
  status          TEXT NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'paid', 'partial')),
  note            TEXT,
  paid_at         TIMESTAMPTZ,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Coach can access payments of their own clients
CREATE POLICY "Coach access payments" ON payments
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM clients c
      WHERE c.id = payments.client_id
        AND c.coach_email = (auth.jwt() ->> 'email')
    )
  );

-- Indexes
CREATE INDEX IF NOT EXISTS idx_payments_client_id ON payments(client_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
