-- ============================================================
-- PAYMENTS V2
-- Run in Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS payments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id          BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  package_id         UUID REFERENCES packages(id) ON DELETE SET NULL,
  package_number     INT,
  amount             BIGINT NOT NULL DEFAULT 0,
  status             TEXT NOT NULL DEFAULT 'pending',
  payment_type       TEXT NOT NULL DEFAULT 'package',
  title              TEXT,
  note               TEXT,
  detail_note        TEXT,
  payment_method     TEXT,
  created_by         TEXT NOT NULL DEFAULT 'coach',
  customer_marked_at TIMESTAMPTZ,
  coach_confirmed_at TIMESTAMPTZ,
  paid_at            TIMESTAMPTZ,
  cancelled_at       TIMESTAMPTZ,
  created_at         TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS payment_type TEXT NOT NULL DEFAULT 'package',
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS detail_note TEXT,
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT NOT NULL DEFAULT 'coach',
  ADD COLUMN IF NOT EXISTS customer_marked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS coach_confirmed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;

UPDATE payments
SET status = CASE
  WHEN status = 'unpaid' THEN 'pending'
  WHEN status = 'partial' THEN 'submitted'
  ELSE status
END;

UPDATE payments
SET payment_type = 'package'
WHERE payment_type IS NULL;

UPDATE payments
SET title = COALESCE(
  title,
  CASE
    WHEN package_number IS NOT NULL THEN 'Package #' || LPAD(package_number::TEXT, 2, '0')
    ELSE 'Service Payment'
  END
)
WHERE title IS NULL;

UPDATE payments
SET detail_note = COALESCE(detail_note, note)
WHERE detail_note IS NULL
  AND note IS NOT NULL;

ALTER TABLE payments
  ALTER COLUMN status SET DEFAULT 'pending',
  ALTER COLUMN payment_type SET DEFAULT 'package',
  ALTER COLUMN created_by SET DEFAULT 'coach';

DO $$
DECLARE
  constraint_row RECORD;
BEGIN
  FOR constraint_row IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    WHERE rel.relname = 'payments'
      AND con.contype = 'c'
      AND (
        pg_get_constraintdef(con.oid) ILIKE '%status%'
        OR pg_get_constraintdef(con.oid) ILIKE '%payment_type%'
      )
  LOOP
    EXECUTE format('ALTER TABLE payments DROP CONSTRAINT IF EXISTS %I', constraint_row.conname);
  END LOOP;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'payments_status_check_v2'
  ) THEN
    ALTER TABLE payments
      ADD CONSTRAINT payments_status_check_v2
      CHECK (status IN ('pending', 'submitted', 'paid', 'cancelled'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'payments_type_check_v2'
  ) THEN
    ALTER TABLE payments
      ADD CONSTRAINT payments_type_check_v2
      CHECK (payment_type IN ('package', 'nutrition', 'prep_meal', 'stretching', 'other'));
  END IF;
END $$;

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Coach access payments" ON payments;
CREATE POLICY "Coach access payments" ON payments
  FOR ALL USING (
    EXISTS (
      SELECT 1
      FROM clients c
      WHERE c.id = payments.client_id
        AND c.coach_email = (auth.jwt() ->> 'email')
    )
  );

DROP POLICY IF EXISTS "Client read own payments" ON payments;
CREATE POLICY "Client read own payments" ON payments
  FOR SELECT USING (
    EXISTS (
      SELECT 1
      FROM clients c
      WHERE c.id = payments.client_id
        AND c.auth_user_id = auth.uid()
    )
  );

CREATE INDEX IF NOT EXISTS idx_payments_client_id ON payments(client_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_type ON payments(payment_type);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at DESC);

CREATE OR REPLACE FUNCTION client_submit_payment(p_payment_id BIGINT)
RETURNS payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payment payments;
BEGIN
  UPDATE payments AS p
  SET status = 'submitted',
      customer_marked_at = COALESCE(p.customer_marked_at, NOW())
  WHERE p.id = p_payment_id
    AND p.status = 'pending'
    AND EXISTS (
      SELECT 1
      FROM clients c
      WHERE c.id = p.client_id
        AND c.auth_user_id = auth.uid()
    )
  RETURNING p.* INTO v_payment;

  IF v_payment.id IS NULL THEN
    RAISE EXCEPTION 'Payment not found or cannot be submitted.';
  END IF;

  RETURN v_payment;
END;
$$;

GRANT EXECUTE ON FUNCTION client_submit_payment(BIGINT) TO authenticated;
